def generate_ascii():
    for row in range(1, 26):
        line = ""
        for column in range(80):
            char = " "

            if row == 1:
                if 0 <= column <= 37: char = '@'
                elif 38 <= column <= 39: char = '&'
                elif 40 <= column <= 43: char = '#'
                elif 44 <= column <= 47: char = '&'
                elif 48 <= column <= 79: char = '@'

            if row == 2:
                if 0 <= column <= 33: char = '@'
                elif 34 <= column <= 35: char = '&'
                elif column == 36: char = '#'
                elif 37 <= column <= 47: char = 'S'
                elif column == 48: char = '#'
                elif 49 <= column <= 79: char = '@'

            if row == 3:
                if 0 <= column <= 32: char = '@'
                elif column == 33: char = '#'
                elif 34 <= column <= 43: char = 'S'
                elif 44 <= column <= 45: char = '#'
                elif 46 <= column <= 48: char = 'S'
                elif column == 49: char = '#'
                elif column == 50: char = '&'
                elif 51 <= column <= 79: char = '@'

            if row == 4:
                if 0 <= column <= 30: char = '@'
                elif column == 31: char = '&'
                elif column == 32: char = '#'
                elif 33 <= column <= 41: char = 'S'
                elif column == 42: char = '#'
                elif 43 <= column <= 44: char = '&'
                elif 45 <= column <= 47: char = 'S'
                elif 48 <= column <= 49: char = '#'
                elif column == 50: char = 'S'
                elif column == 51: char = '&'
                elif 52 <= column <= 79: char = '@'

            if row == 5:
                if 0 <= column <= 29: char = '@'
                elif column == 30: char = '&'
                elif 31 <= column <= 34: char = '#'
                elif 35 <= column <= 37: char = 'S'
                elif column == 38: char = '&'
                elif column == 39: char = '@'
                elif 40 <= column <= 41: char = '$'
                elif 42 <= column <= 43: char = '%'
                elif column == 44: char = '$'
                elif column == 45: char = '#'
                elif 46 <= column <= 47: char = 'S'
                elif 48 <= column <= 51: char = '#'
                elif 52 <= column <= 79: char = '@'

            if row == 6:
                if 0 <= column <= 29: char = '@'
                elif 30 <= column <= 31: char = '#'
                elif column == 32: char = 'S'
                elif column == 33: char = '#'
                elif column == 34: char = 'S'
                elif column == 35: char = '*'
                elif column == 36: char = 'S'
                elif column == 37: char = '$'
                elif 38 <= column <= 44: char = '*'
                elif column == 45: char = '$'
                elif column == 46: char = '#'
                elif 47 <= column <= 49: char = 'S'
                elif column == 50: char = '#'
                elif column == 51: char = 'S'
                elif column == 52: char = '#'
                elif 53 <= column <= 79: char = '@'

            if row == 7:
                if 0 <= column <= 27: char = '@'
                elif column == 28: char = '&'
                elif 29 <= column <= 30: char = '#'
                elif 31 <= column <= 34: char = '*'
                elif column == 35: char = '#'
                elif column == 36: char = '$'
                elif column == 37: char = '%'
                elif 38 <= column <= 43: char = '*'
                elif 44 <= column <= 45: char = '%'
                elif column == 46: char = '$'
                elif column == 47: char = '&'
                elif 48 <= column <= 49: char = '*'
                elif 50 <= column <= 52: char = 'S'
                elif column == 53: char = '#'
                elif 54 <= column <= 79: char = '@'

            if row == 8:
                if 0 <= column <= 26: char = '@'
                elif column == 27: char = '&'
                elif 28 <= column <= 29: char = 'S'
                elif 30 <= column <= 33: char = '*'
                elif column == 34: char = '#'
                elif column == 35: char = '$'
                elif 36 <= column <= 37: char = '@'
                elif column == 38: char = '&'
                elif column == 39: char = '@'
                elif column == 40: char = '$'
                elif column == 41: char = '*'
                elif column == 42: char = '%'
                elif column == 43: char = '@'
                elif 44 <= column <= 45: char = '&'
                elif 46 <= column <= 47: char = '@'
                elif column == 48: char = '&'
                elif 49 <= column <= 51: char = '*'
                elif 52 <= column <= 54: char = 'S'
                elif column == 55: char = '&'
                elif 56 <= column <= 79: char = '@'

            if row == 9:
                if 0 <= column <= 26: char = '@'
                elif column == 27: char = '#'
                elif column == 28: char = 'S'
                elif 29 <= column <= 33: char = '*'
                elif column == 34: char = '@'
                elif column == 35: char = '$'
                elif 36 <= column <= 38: char = '@'
                elif 39 <= column <= 40: char = '$'
                elif column == 41: char = '*'
                elif column == 42: char = '$'
                elif 43 <= column <= 46: char = '@'
                elif column == 47: char = '$'
                elif column == 48: char = '@'
                elif column == 49: char = 'S'
                elif 50 <= column <= 52: char = '*'
                elif 53 <= column <= 55: char = 'S'
                elif 56 <= column <= 79: char = '@'

            if row == 10:
                if 0 <= column <= 25: char = '@'
                elif column == 26: char = '&'
                elif 27 <= column <= 28: char = 'S'
                elif 29 <= column <= 32: char = '*'
                elif column == 33: char = 'S'
                elif column == 34: char = '@'
                elif column == 35: char = '%'
                elif column == 36: char = '*'
                elif 37 <= column <= 40: char = '%'
                elif column == 41: char = '*'
                elif 42 <= column <= 47: char = '%'
                elif column == 48: char = '$'
                elif column == 49: char = '&'
                elif column == 50: char = '#'
                elif 51 <= column <= 54: char = '*'
                elif column == 55: char = 'S'
                elif 56 <= column <= 79: char = '@'

            if row == 11:
                if 0 <= column <= 25: char = '@'
                elif column == 26: char = '#'
                elif 27 <= column <= 32: char = '*'
                elif column == 33: char = 'S'
                elif column == 34: char = '@'
                elif 35 <= column <= 40: char = '%'
                elif column == 41: char = '*'
                elif column == 42: char = '%'
                elif column == 43: char = '$'
                elif 44 <= column <= 47: char = '%'
                elif column == 48: char = '$'
                elif column == 49: char = '&'
                elif column == 50: char = '#'
                elif 51 <= column <= 54: char = '*'
                elif column == 55: char = '#'
                elif 56 <= column <= 79: char = '@'

            if row == 12:
                if 0 <= column <= 25: char = '@'
                elif column == 26: char = '#'
                elif 27 <= column <= 33: char = '*'
                elif column == 34: char = '&'
                elif 35 <= column <= 38: char = '$'
                elif 39 <= column <= 41: char = '%'
                elif 42 <= column <= 48: char = '$'
                elif 49 <= column <= 53: char = '*'
                elif column == 54: char = 'S'
                elif column == 55: char = '&'
                elif 56 <= column <= 79: char = '@'

            if row == 13:
                if 0 <= column <= 25: char = '@'
                elif column == 26: char = '#'
                elif column == 27: char = 'S'
                elif 28 <= column <= 31: char = '*'
                elif column == 32: char = 'S'
                elif column == 33: char = '*'
                elif column == 34: char = 'S'
                elif column == 35: char = '$'
                elif 36 <= column <= 37: char = '%'
                elif 38 <= column <= 39: char = '$'
                elif 40 <= column <= 42: char = '%'
                elif 43 <= column <= 44: char = '$'
                elif 45 <= column <= 46: char = '%'
                elif column == 47: char = '$'
                elif column == 48: char = '&'
                elif 49 <= column <= 53: char = '*'
                elif column == 54: char = 'S'
                elif 55 <= column <= 79: char = '@'

            if row == 14:
                if 0 <= column <= 24: char = '@'
                elif column == 25: char = '#'
                elif column == 26: char = 'S'
                elif 27 <= column <= 34: char = '*'
                elif column == 35: char = 'S'
                elif column == 36: char = '$'
                elif 37 <= column <= 38: char = '*'
                elif column == 39: char = '%'
                elif column == 40: char = '*'
                elif 41 <= column <= 42: char = '%'
                elif 43 <= column <= 44: char = '*'
                elif column == 45: char = '%'
                elif column == 46: char = '$'
                elif column == 47: char = '#'
                elif 48 <= column <= 53: char = '*'
                elif column == 54: char = 'S'
                elif column == 55: char = '#'
                elif 56 <= column <= 79: char = '@'

            if row == 15:
                if 0 <= column <= 23: char = '@'
                elif column == 24: char = '&'
                elif column == 25: char = '#'
                elif column == 26: char = 'S'
                elif 27 <= column <= 35: char = '*'
                elif column == 36: char = 'S'
                elif column == 37: char = '&'
                elif column == 38: char = '$'
                elif column == 39: char = '%'
                elif 40 <= column <= 42: char = '*'
                elif column == 43: char = '%'
                elif column == 44: char = '$'
                elif column == 45: char = '@'
                elif column == 46: char = 'S'
                elif 47 <= column <= 53: char = '*'
                elif 54 <= column <= 55: char = 'S'
                elif column == 56: char = '#'
                elif 57 <= column <= 79: char = '@'

            if row == 16:
                if 0 <= column <= 22: char = '@'
                elif column == 23: char = '&'
                elif column == 24: char = '#'
                elif column == 25: char = 'S'
                elif 26 <= column <= 37: char = '*'
                elif column == 38: char = 'S'
                elif column == 39: char = '@'
                elif 40 <= column <= 42: char = '$'
                elif column == 43: char = '@'
                elif column == 44: char = '&'
                elif 45 <= column <= 52: char = '*'
                elif 53 <= column <= 56: char = 'S'
                elif 57 <= column <= 79: char = '@'

            if row == 17:
                if 0 <= column <= 22: char = '@'
                elif column == 23: char = '&'
                elif column == 24: char = '#'
                elif column == 25: char = 'S'
                elif column == 26: char = '*'
                elif 27 <= column <= 28: char = 'S'
                elif 29 <= column <= 38: char = '*'
                elif column == 39: char = '#'
                elif column == 40: char = '@'
                elif 41 <= column <= 42: char = '$'
                elif column == 43: char = '@'
                elif column == 44: char = 'S'
                elif 45 <= column <= 52: char = '*'
                elif column == 53: char = 'S'
                elif column == 54: char = '*'
                elif column == 55: char = 'S'
                elif column == 56: char = '#'
                elif 57 <= column <= 79: char = '@'

            if row == 18:
                if 0 <= column <= 23: char = '@'
                elif column == 24: char = '$'
                elif column == 25: char = '&'
                elif 26 <= column <= 27: char = 'S'
                elif 28 <= column <= 30: char = '*'
                elif column == 31: char = '#'
                elif column == 32: char = 'S'
                elif 33 <= column <= 38: char = '*'
                elif column == 39: char = '#'
                elif column == 40: char = '&'
                elif 41 <= column <= 42: char = '$'
                elif column == 43: char = '&'
                elif 44 <= column <= 54: char = '*'
                elif column == 55: char = 'S'
                elif 56 <= column <= 57: char = '#'
                elif column == 58: char = '&'
                elif 59 <= column <= 79: char = '@'

            if row == 19:
                if 0 <= column <= 19: char = '@'
                elif column == 20: char = '$'
                elif column == 21: char = '*'
                elif 22 <= column <= 23: char = '!'
                elif 24 <= column <= 25: char = ':'
                elif column == 26: char = '%'
                elif column == 27: char = '#'
                elif column == 28: char = 'S'
                elif 29 <= column <= 31: char = '*'
                elif column == 32: char = 'S'
                elif column == 33: char = '#'
                elif column == 34: char = 'S'
                elif 35 <= column <= 38: char = '*'
                elif column == 39: char = 'S'
                elif column == 40: char = '#'
                elif 41 <= column <= 42: char = '&'
                elif column == 43: char = '#'
                elif 44 <= column <= 45: char = 'S'
                elif 46 <= column <= 54: char = '*'
                elif 55 <= column <= 57: char = 'S'
                elif column == 58: char = '#'
                elif 59 <= column <= 79: char = '@'

            if row == 20:
                if 0 <= column <= 16: char = '@'
                elif column == 17: char = '$'
                elif column == 18: char = '*'
                elif column == 19: char = '!'
                elif column == 20: char = ':'
                elif column == 21: char = '!'
                elif 22 <= column <= 25: char = ':'
                elif column == 26: char = '!'
                elif column == 27: char = '*'
                elif column == 28: char = '@'
                elif column == 29: char = '&'
                elif column == 30: char = 'S'
                elif 31 <= column <= 32: char = '#'
                elif column == 33: char = '&'
                elif 34 <= column <= 35: char = '@'
                elif column == 36: char = '&'
                elif column == 37: char = 'S'
                elif 38 <= column <= 39: char = '*'
                elif 40 <= column <= 42: char = 'S'
                elif column == 43: char = '#'
                elif column == 44: char = 'S'
                elif 45 <= column <= 54: char = '*'
                elif 55 <= column <= 58: char = 'S'
                elif column == 59: char = '&'
                elif column == 60: char = '%'
                elif column == 61: char = '$'
                elif 62 <= column <= 79: char = '@'

            if row == 21:
                if 0 <= column <= 14: char = '@'
                elif column == 15: char = '%'
                elif column == 16: char = '*'
                elif 17 <= column <= 19: char = ':'
                elif column == 20: char = '!'
                elif 21 <= column <= 22: char = '*'
                elif 23 <= column <= 28: char = '!'
                elif column == 29: char = '*'
                elif column == 30: char = '@'
                elif column == 31: char = '#'
                elif column == 32: char = '@'
                elif 33 <= column <= 34: char = '%'
                elif column == 35: char = '$'
                elif 36 <= column <= 38: char = '@'
                elif 39 <= column <= 40: char = 'S'
                elif column == 41: char = '#'
                elif column == 42: char = '&'
                elif column == 43: char = '@'
                elif 44 <= column <= 45: char = '#'
                elif column == 46: char = 'S'
                elif 47 <= column <= 50: char = '*'
                elif 51 <= column <= 56: char = 'S'
                elif column == 57: char = '#'
                elif 58 <= column <= 59: char = 'S'
                elif column == 60: char = '*'
                elif column == 61: char = '!'
                elif 62 <= column <= 63: char = '*'
                elif column == 64: char = '$'
                elif 65 <= column <= 79: char = '@'

            if row == 22:
                if 0 <= column <= 12: char = '@'
                elif column == 13: char = '$'
                elif 14 <= column <= 19: char = '!'
                elif column == 20: char = ':'
                elif 21 <= column <= 29: char = '!'
                elif column == 30: char = ':'
                elif 31 <= column <= 33: char = '!'
                elif 34 <= column <= 35: char = ':'
                elif 36 <= column <= 38: char = '!'
                elif column == 39: char = '%'
                elif column == 40: char = '$'
                elif 41 <= column <= 43: char = '@'
                elif 44 <= column <= 45: char = '&'
                elif column == 46: char = '#'
                elif 47 <= column <= 48: char = 'S'
                elif 49 <= column <= 50: char = '*'
                elif 51 <= column <= 59: char = 'S'
                elif column == 60: char = '%'
                elif column == 61: char = '*'
                elif 62 <= column <= 63: char = '!'
                elif column == 64: char = '*'
                elif column == 65: char = '%'
                elif 66 <= column <= 79: char = '@'

            if row == 23:
                if 0 <= column <= 11: char = '@'
                elif column == 12: char = '%'
                elif 13 <= column <= 25: char = '!'
                elif 26 <= column <= 27: char = '*'
                elif 28 <= column <= 29: char = '!'
                elif 30 <= column <= 31: char = ':'
                elif column == 32: char = '!'
                elif column == 33: char = '*'
                elif 34 <= column <= 35: char = '%'
                elif 36 <= column <= 37: char = '$'
                elif 38 <= column <= 41: char = '%'
                elif 42 <= column <= 43: char = '!'
                elif 44 <= column <= 45: char = '*'
                elif column == 46: char = '$'
                elif column == 47: char = '@'
                elif column == 48: char = '&'
                elif 49 <= column <= 50: char = '$'
                elif column == 51: char = '@'
                elif column == 52: char = '&'
                elif column == 53: char = '#'
                elif 54 <= column <= 55: char = '*'
                elif 56 <= column <= 57: char = 'S'
                elif column == 58: char = '@'
                elif column == 59: char = '$'
                elif 60 <= column <= 62: char = '*'
                elif column == 63: char = '%'
                elif column == 64: char = '*'
                elif column == 65: char = '!'
                elif column == 66: char = '%'
                elif 67 <= column <= 79: char = '@'

            if row == 24:
                if 0 <= column <= 9: char = '@'
                elif column == 10: char = '%'
                elif 11 <= column <= 24: char = ':'
                elif 25 <= column <= 26: char = '!'
                elif column == 27: char = '*'
                elif 28 <= column <= 29: char = '$'
                elif column == 30: char = '%'
                elif column == 31: char = '*'
                elif column == 32: char = '%'
                elif 33 <= column <= 41: char = '&'
                elif column == 42: char = '!'
                elif 43 <= column <= 44: char = ':'
                elif column == 45: char = '!'
                elif column == 46: char = '*'
                elif column == 47: char = '@'
                elif column == 48: char = 'S'
                elif column == 49: char = '%'
                elif column == 50: char = ':'
                elif column == 51: char = '!'
                elif column == 52: char = '*'
                elif column == 53: char = '%'
                elif column == 54: char = '@'
                elif column == 55: char = '$'
                elif column == 56: char = '*'
                elif column == 57: char = '@'
                elif column == 58: char = '#'
                elif column == 59: char = '$'
                elif column == 60: char = '%'
                elif 61 <= column <= 62: char = '$'
                elif 63 <= column <= 64: char = '%'
                elif column == 65: char = '*'
                elif column == 66: char = '!'
                elif column == 67: char = '%'
                elif 68 <= column <= 79: char = '@'

            if row == 25:
                if 0 <= column <= 8: char = '@'
                elif column == 9: char = '$'
                elif 10 <= column <= 26: char = ':'
                elif column == 27: char = '!'
                elif column == 28: char = '*'
                elif 29 <= column <= 30: char = '@'
                elif 31 <= column <= 34: char = '!'
                elif 35 <= column <= 41: char = '*'
                elif 42 <= column <= 46: char = '!'
                elif column == 47: char = '*'
                elif 48 <= column <= 49: char = '%'
                elif column == 50: char = '!'
                elif column == 51: char = '*'
                elif 52 <= column <= 54: char = '!'
                elif column == 55: char = ':'
                elif column == 56: char = '!'
                elif column == 57: char = '$'
                elif column == 58: char = '*'
                elif column == 59: char = '%'
                elif column == 60: char = '&'
                elif column == 61: char = '@'
                elif column == 62: char = '%'
                elif column == 63: char = '*'
                elif 64 <= column <= 65: char = '!'
                elif column == 66: char = ':'
                elif column == 67: char = '*'
                elif 68 <= column <= 79: char = '@'

            line += char
        print(line)

generate_ascii()
